framework:
    zookeeper:
        connectionString: localhost:2181
        namespace: ring/lock
        sessionTimeoutMs: 60000
        connectionTimeoutMs: 15000
spring:
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.jdbc.Driver
        druid:
            url: jdbc:mysql://localhost:3306/ring?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
            username: root
            password:
            initial-size: 10
            max-active: 20
            min-idle: 5
            max-wait: 60000 # 配置获取连接等待超时的时间
            pool-prepared-statements: true
            max-pool-prepared-statement-per-connection-size: 20
            # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
            time-between-eviction-runs-millis: 60000
            # 连接保持空闲而不被驱逐的最长时间
            min-evictable-idle-time-millis: 300000
            validation-query: SELECT 1 FROM DUAL # 配置一个连接在池中最小生存的时间，单位是毫秒
            test-while-idle: true
            test-on-borrow: false
            test-on-return: false
            stat-view-servlet:
                enabled: true
                url-pattern: /druid/*
                login-username:
                login-password:
            filter:
                stat:
                    log-slow-sql: true
                    slow-sql-millis: 1000
                    merge-sql: true
                wall:
                    config:
                        multi-statement-allow: true
    redis:
        open: false  # 是否开启redis缓存  true开启   false关闭
        database: 0
        host: 10.50.10.203
        port: 6379
        password:       # 密码（默认为空）
        timeout: 6000  # 连接超时时长（毫秒）
        pool:
            max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
            max-wait: -1      # 连接池最大阻塞等待时间（使用负值表示没有限制）
            max-idle: 10      # 连接池中的最大空闲连接
            min-idle: 5       # 连接池中的最小空闲连接
    rabbitmq:
      host: 10.1.2.104
      port: 9104
      username: guest
      password: guest
      publisher-confirms: true
      publisher-returns: true
      template:
         mandatory: true
      listener:
         simple:
            concurrency: 1
            max-concurrency: 1
    mail:
       host: smtp.exmail.qq.com
       username: 123456@qq.com
       password: 123456
       default-encoding: UTF-8

