framework:
    swagger-open: true #开启接口
    http:
       socketTimeout: 30000
       connectTimeout: 30000
       connectionRequestTimeout: 200
       maxTotal: 1000
    executor:
       corePoolSize: 5
       maxPoolSize: 5
       queueCapacity: 5
       keepAliveSeconds: 5
spring:
    # 环境 dev|test|pro
    profiles:
        active: dev
    # jackson时间格式化
    jackson:
        time-zone: GMT+8
        date-format: yyyy-MM-dd HH:mm:ss
    http:
        multipart:
            max-file-size: 100MB
            max-request-size: 100MB
            enabled: true
        encoding:
            charset: UTF-8
            enabled: true
            force: true
    #resources: # 指定静态资源的路径
        #static-locations: classpath:/static/,classpath:/views/
# Tomcat
server:
    tomcat:
        uri-encoding: UTF-8
        max-threads: 1000
        min-spare-threads: 30
    port: 8081
    connection-timeout: 5000
    context-path: /
logging:
    config : classpath:logback-spring.xml
#Mybatis
mybatis:
    type-aliase-package: com.ring.api.model
    mapper-locations : classpath*:mapper/*.xml
    config-location : classpath:mybatis-config.xml
    base-package : com.ring.core.mapper

